config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w(chinese italian japanese french belgian) %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container mt-5">
  <%= render 'form' %>

</div>

app/views/restaurants/index.html.erb
<div class="container mt-5 col-6">
  <h1>Restaurants</h1>
  <ul><% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant, class:"text-decoration-none" %><%= link_to restaurant_path(restaurant),
              method: :delete,
              data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt"></i>
              <% end %></li>
  <% end %></ul>
  <button class="btn btn-secondary"><%= link_to "Create New", new_restaurant_path, class:"text-white" %></button>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h2>Create New Restaurant</h2>
  <%= render 'form' %>

  <button class="btn btn-secondary mt-3"><%= link_to "Back", restaurants_path, class:"text-white" %></button>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5 col-6">

  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
  <div class="d-grid gap-3 list-unstyled">
    <% @restaurant.reviews.each do |review| %>
    <div class="p-2 bg-light border d-flex justify-content-between">
    <%= review.content %>
    <%= link_to review_path(review),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <i class="fas fa-trash-alt"></i>
                    <% end %></div>
    <% end %>
  </div>

    <button class="btn btn-secondary m-3"><%= link_to 'Back', restaurants_path, class:"text-white" %></button>
    <button class="btn btn-secondary m-3"><%= link_to 'Update', edit_restaurant_path, class:"text-white" %></button>
    <button class="btn btn-secondary m-3"><%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class:"text-white" %></button>

</div>

app/views/reviews/new.html.erb
<div class="container mt-5 col-6">
  <h3>New Review for <%= @restaurant.name %> </h3>
  <%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 0..5 %>
    <%= f.submit "Submit review", class: "btn btn-secondary" %>
  <% end %>

  <button class="btn btn-secondary mt-3"><%= link_to "Back", restaurant_reviews_path, class:"text-white" %></button>
</div>